/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "multas.h"
#define cls system("clear")
#define pausa(seconds) {system("sleep "#seconds);printf("Pulsa enter para continuar...");fflush(stdout); system("read a");}

int menu(){
	int opcion;
        do {
            printf("\nMenu Consultas\n");
            printf("*********************\n\n");
            printf("1.- Identificación\n");
            printf("2.- Consultar puntos\n");
            printf("3.- Consultar multas\n");
            printf("4.- Salir\n");
            scanf("%d", &opcion);	
        } while (opcion < 1 || opcion > 4);

        return opcion;
}

void
multas_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	ST_DatosUsuario  comprobarpuntos_1_arg;
	ST_DatosMultas  *result_2;
	ST_DatosUsuario  comprobarmultas_1_arg;
	int  *result_3;
	char  identificacion_1_arg;
	int  *result_4;
	ST_DatosSancion  ponermulta_1_arg;
	int  *result_5;
	ST_DatosSancion  quitarmulta_1_arg;
	int  *result_6;
	ST_DatosUsuario  altavehiculo_1_arg;
	int  *result_7;
	ST_DatosUsuario  bajavehiculo_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MULTAS, MULTAS_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = comprobarpuntos_1(&comprobarpuntos_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = comprobarmultas_1(&comprobarmultas_1_arg, clnt);
	if (result_2 == (ST_DatosMultas *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = identificacion_1(&identificacion_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = ponermulta_1(&ponermulta_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = quitarmulta_1(&quitarmulta_1_arg, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = altavehiculo_1(&altavehiculo_1_arg, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = bajavehiculo_1(&bajavehiculo_1_arg, clnt);
	if (result_7 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	
	CLIENT *clnt;
	
	int *res, opcion, puntosSancion, dni;
	T_String password, fecha, matricula;
	ST_DatosUsuario usuarios;
	ST_DatosMultas *multas = NULL;
	ST_DatosSancion sanciones;

	clnt = clnt_create (host, MULTAS, MULTAS_VER, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}	
	
	printf("Cliente: Tengo Conexion con el servidor comenzamos\n\n");
	
	do
	{
		cls;
		opcion = menu();

		switch(opcion){
			case 1:
				cls;
				printf("Introducir password: \n");
				scanf("%s", password);

				res = identificacion_1(password, clnt);
				if(res != (int *) NULL){
					if(*res == 1){
						printf("Identificacion correcta\n\n");
						pausa(2);

						do{
							cls;
							printf("\nMenú Gestión\n");
							printf("*********************\n\n");
							printf("1.- Poner Multa\n");
							printf("2.- Quitar Multa\n");
							printf("3.- Alta de un Vehiculo\n");
							printf("4.- Baja de un Vehiculo\n");
							printf("5.- Salir\n");
							printf("Elige una opcion: \n");
							scanf("%d", &opcion);

							switch(opcion){
								case 1:
									cls;
									printf("Introducir matricula: \n");
									scanf("%s", matricula);
									strcpy(sanciones.Matricula, matricula);
									printf("Introducir fecha: \n");
									scanf("%s", fecha);
									strcpy(sanciones.Fecha, fecha);
									printf("Introducir número de puntos de la sanción: \n");
									scanf("%d", &puntosSancion);
									sanciones.Puntos = puntosSancion;
									res = ponermulta_1(&sanciones, clnt);
									if(res != (int *) NULL){
										if(*res == 1){	
											printf("Multa añadida correctamente. Vehículo con matricula: %s", matricula);
											pausa(2);
										}
										else{
											printf("La multa no se ha añadido\n");
											pausa(2);
										}	
									}
									else
										clnt_perror (clnt, "Cliente: Error en la llamada al procedimiento PONER MULTA.");
								break;
								case 2:
									cls;
									printf("Introducir matricula: \n");
									scanf("%s", matricula);
									strcpy(sanciones.Matricula, matricula);
									printf("Introducir fecha: \n");
									scanf("%s", fecha);
									strcpy(sanciones.Fecha, fecha);
									res = quitarmulta_1(&sanciones, clnt);
									if(res != (int *) NULL){
										if(*res == 1){
											printf("Multa borrada del sistema");
											pausa(2);
										}
										else{
											printf("No se ha podido eliminar la multa\n");
											pausa(2);
										}
									}
									else
										clnt_perror (clnt, "Cliente: Error en la llamada al procedimiento QUITAR MULTA.");
								break;
								case 3:
									cls;
									printf("Introducir dni: \n");
									scanf("%d", &dni);
									usuarios.Dni = dni;
									printf("Introducir matricula: \n");
									scanf("%s", matricula);
									strcpy(usuarios.Matricula, matricula);
									res = altavehiculo_1(&usuarios, clnt);
									if(res != (int *) NULL){
										if(*res == 1){
											printf("Vehículo dado de alta correctamente\n");
											pausa(2);
										}
										else{
											printf("El Vehículo no se ha dado de alta\n");
											pausa(2);
										}
									}
									else
										clnt_perror (clnt, "Cliente: Error en la llamada al procedimiento ALTA VEHICULO.");
								break;
								case 4:
									cls;
									printf("Introducir dni: \n");
									scanf("%d", &dni);
									usuarios.Dni = dni;
									printf("Introducir matricula: \n");
									scanf("%s", matricula);
									strcpy(usuarios.Matricula, matricula);
									res = bajavehiculo_1(&usuarios, clnt);
									if(res != (int *) NULL){
										if(*res == 1){
											printf("Vehículo dado de baja correctamente\n");
											pausa(2);
										}
										else if(*res == 0){
											printf("El Vehículo no se ha dado de baja ya que tiene multas pendientes\n");
											pausa(2);
										}	
										else{
											printf("Vehículo no encontrado en el sistema\n");
											pausa(2);
										}
									}
									else
										clnt_perror (clnt, "Cliente: Error en la llamada al procedimiento BAJA VEHICULO.");
								break;
							}
						}while(opcion != 5);
					}
					else{
						printf("Password incorrecto");
						pausa(2);
					}
				}
				else
					clnt_perror (clnt, "Cliente: Error en la llamada al procedimiento IDENTIFICACION.");
			break;
			case 2:
				cls;
				printf("Introducir dni: \n");
				scanf("%d", &dni);
				usuarios.Dni = dni;
				printf("Introducir matricula: \n");
				scanf("%s", matricula);
				strcpy(usuarios.Matricula, matricula);
				res = comprobarpuntos_1(&usuarios, clnt);
				if(res != (int *) NULL){
					if(*res == -1){
						printf("Usuario no encontrado en el sistema\n");
						pausa(2);
					}
					else{
						printf("El usuario tiene %d puntos\n", *res);
						pausa(2);
					}
				}
				else
					clnt_perror (clnt, "Cliente: Error en la llamada al procedimiento CONSULTAR PUNTOS.");
			break;
			case 3:
				cls;
				printf("Introducir dni: \n");
				scanf("%d", &dni);
				usuarios.Dni = dni;
				printf("Introducir matricula: \n");
				scanf("%s", matricula);
				strcpy(usuarios.Matricula, matricula);
				multas = comprobarmultas_1(&usuarios, clnt);
				if(multas != (ST_DatosMultas *) NULL){
					printf("Vehiculo con %d multas\n", multas->NumeMultas);
					printf("\n %s \n", multas->ListadoMultas);
					pausa(2);
				}
				else
					clnt_perror (clnt, "Cliente: Error en la llamada al procedimiento CONSULTAR MULTAS.");
			break;
		}
	}while(opcion != 4);
	printf("Cliente: Hemos terminado. Hasta otra\n\n");
	clnt_destroy(clnt);
exit (0);
}
