/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "multas.h"
#include <stdbool.h>

ST_DatosSancion sanciones[100]; //Matricula, fecha, puntos aplicados a la sancion
ST_DatosUsuario usuarios[100]; //Dni y Matricula
int nSanciones = 0;  //Contador sanciones
int nUsuarios = 0;   //Contador usuarios


/************************   COMPROBAR_PUNTOS   ************************
	Dado los datos de un usuario (DNI y Matricula) la funcion comprobará
	que el vehiculo esta dado de alta y devolverá los puntos asociados al
	usuario. Si no se encuentra el usuario devolvera -1
*/
int * comprobarpuntos_1_svc(ST_DatosUsuario *argp, struct svc_req *rqstp){
	static int  result;
	int puntos = 0;

	if(nUsuarios == 0){
		result = -1;
		printf("No existen usuarios");
	}else{
		for(int i=0; i < nUsuarios; i++){
			if(argp->Dni == usuarios[i].Dni && strcmp(usuarios[i].Matricula, argp->Matricula) == 0){
				for(int j=0; j < nSanciones; j++){
					if(strcmp(sanciones[j].Matricula, argp->Matricula) == 0){
						puntos = puntos + sanciones[j].Puntos;
					}			
				}
				result = 15 - puntos;
			}else {
				result = -1;
				printf("Usuario no encontrado");		
			}
		}
	}	
	return &result;
}


/************************   COMPROBAR_MULTAS   ************************
	Dado los datos de un usuario (DNI y Matricula) la funcion comprobará
	que el vehiculo esta dado de alta y devolverá los datos de las multas
	que son:
	- El numero de multas que tiene el vehiculo del usuario
	- El listado de multas (Matricula, Fecha y Puntos perdidos)
*/
ST_DatosMultas * comprobarmultas_1_svc(ST_DatosUsuario *argp, struct svc_req *rqstp){
	static ST_DatosMultas  result;
	strcpy(result.ListadoMultas, "");
	result.NumeMultas = 0;
	T_Listado multas;
	
	for(int i=0; i < nUsuarios; i++){
		if(argp->Dni == usuarios[i].Dni && strcmp(usuarios[i].Matricula, argp->Matricula) == 0){
			for(int j=0; j < nSanciones; j++){
				if(strcmp(sanciones[j].Matricula, argp->Matricula) == 0){
					result.NumeMultas++;
					sprintf(multas, "Matricula: %s \n, Fecha: %s \n, Puntos: %d \n", 
						sanciones[j].Matricula, 
						sanciones[j].Fecha, 
						sanciones[j].Puntos);
					strcat(result.ListadoMultas, multas);
				}			
			}	
		}else {
			printf("Usuario no encontrado");
		}
	}
	return &result;
}

/************************   IDENTIFICACION   ************************
	Dado el password del agente la funcion comprobara si coincide
	con el 541293AGP. Si coincide devuelve 1 si no devuelve 0
*/
int * identificacion_1_svc(char *argp, struct svc_req *rqstp){
	static int  result;
	T_String cadena = "1";

	if(strcmp(argp,cadena)==0){	
		result=1;
		printf("Agente identificado");
	} else {
		result=0;
		printf("Agente NO identificado");
	}
	return &result;
}

/************************   PONER_MULTA   ************************
	Dado la sancion (Matricula, Fecha y Puntos perdidos) la 
	almacenara en los datos del Servidor, siempre y cuando la 
	matricula exista. Devuelve 1 si se ha puesto la multa y 0
	en caso contrario.
*/
int * ponermulta_1_svc(ST_DatosSancion *argp, struct svc_req *rqstp){
	static int  result;
	
	for(int i=0; i < nUsuarios; i++){
		if(strcmp(usuarios[i].Matricula, argp->Matricula) == 0){
			strcpy(sanciones[nSanciones].Matricula, argp->Matricula);
			strcpy(sanciones[nSanciones].Fecha, argp->Fecha);
			sanciones[nSanciones].Puntos = argp->Puntos;
			nSanciones++;
			result = 1;
			printf("Multa puesta correctamente");
		}else {
			result = 0;
			printf("Multa no puesta");		
		}
	}

	return &result;
}


/************************   QUITAR_MULTA   ************************
	Dado una Matricula y una Fecha, la funcion devolvera los puntos perdidos
	por la sancion al usuario del vehiculo y eliminado la sancion de los datos 
	del servidor. Devuelve 1 si se ha quitado la multa y 0 en caso contrario.
*/
int * quitarmulta_1_svc(ST_DatosSancion *argp, struct svc_req *rqstp)
{
	static int  result;

	for(int i=0; i < nUsuarios; i++){
		if(strcmp(sanciones[i].Matricula, argp->Matricula) == 0 && strcmp(sanciones[i].Fecha, argp->Fecha) == 0){
			for(int j=i; j<nSanciones-1; j++){
				sanciones[j] = sanciones[j+1];
			}
			nSanciones--;
			result = 1;
			printf("Multa quitada correctamente");
		}else {
			result = 0;
			printf("Multa no quitada");		
		}
	}

	return &result;
}


/************************   ALTA_VEHICULO   ************************
	Dado los datos de un usuario (DNI y Matricula) se da de alta al vehiculo
	en los datos del servidor si previamente no existia dicha matricula. Si 
	se ha dado de alta devolvera 1 en caso contrario 0.
*/
int * altavehiculo_1_svc(ST_DatosUsuario *argp, struct svc_req *rqstp)
{
	static int  result;
	
	if(nUsuarios == 0){
		usuarios[nUsuarios].Dni = argp->Dni;
		strcpy(usuarios[nUsuarios].Matricula, argp->Matricula);
		nUsuarios++;
		result = 1;
		printf("Usuario dado de alta correctamente");
	} else {	
		for(int i=0; i < nUsuarios; i++){
			if(strcmp(usuarios[i].Matricula, argp->Matricula) == 0 && usuarios[i].Dni == argp->Dni){
				result = 0;
				printf("El usuario ya se encuentra en la BD");
			}else {
				usuarios[nUsuarios].Dni = argp->Dni;
				strcpy(usuarios[nUsuarios].Matricula, argp->Matricula);
				nUsuarios++;
				result = 1;
				printf("Usuario dado de alta correctamente");
			}
		}
	}	

	return &result;
}


/************************   BAJA_VEHICULO   ************************
	Dado los datos de un usuario (DNI y Matricula) se da de baja al vehiculo
	en los datos del servidor si previamente existe y no tiene ninguna multa. Si 
	se ha dado de baja devolvera 1 en caso contrario 0.
*/
int * bajavehiculo_1_svc(ST_DatosUsuario *argp, struct svc_req *rqstp)
{
	static int  result;
	bool tieneSancion = false;

	for(int i=0; i < nUsuarios; i++){
		if(strcmp(usuarios[i].Matricula, argp->Matricula) == 0){
			for(int j=0; j < nSanciones; j++){
				if(strcmp(sanciones[j].Matricula, argp->Matricula) == 0){
					tieneSancion = true;
				}
			}
			if(!tieneSancion){
				for(int h=i; h < nUsuarios; h++){
					usuarios[h] = usuarios[h+1];
				}
				result = 1;
				printf("El usuario ha sido dado de baja correctamente");
			} else {
				result = 0;
				printf("El usuario tiene multas pendientes");
			}
		}else {
			result = 0;
			printf("El usuario no se encuentra en la BD");
		}
	}
	return &result;
}
