/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "multas.h"

bool_t
xdr_T_String (XDR *xdrs, T_String objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, 80,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_T_Listado (XDR *xdrs, T_Listado objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, 1500,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ST_DatosUsuario (XDR *xdrs, ST_DatosUsuario *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->Dni))
		 return FALSE;
	 if (!xdr_T_String (xdrs, objp->Matricula))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ST_DatosMultas (XDR *xdrs, ST_DatosMultas *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->NumeMultas))
		 return FALSE;
	 if (!xdr_T_Listado (xdrs, objp->ListadoMultas))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ST_DatosSancion (XDR *xdrs, ST_DatosSancion *objp)
{
	register int32_t *buf;

	 if (!xdr_T_String (xdrs, objp->Matricula))
		 return FALSE;
	 if (!xdr_T_String (xdrs, objp->Fecha))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Puntos))
		 return FALSE;
	return TRUE;
}
