/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "multas.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
multas_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		ST_DatosUsuario comprobarpuntos_1_arg;
		ST_DatosUsuario comprobarmultas_1_arg;
		T_String identificacion_1_arg;
		ST_DatosSancion ponermulta_1_arg;
		ST_DatosSancion quitarmulta_1_arg;
		ST_DatosUsuario altavehiculo_1_arg;
		ST_DatosUsuario bajavehiculo_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case ComprobarPuntos:
		_xdr_argument = (xdrproc_t) xdr_ST_DatosUsuario;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) comprobarpuntos_1_svc;
		break;

	case ComprobarMultas:
		_xdr_argument = (xdrproc_t) xdr_ST_DatosUsuario;
		_xdr_result = (xdrproc_t) xdr_ST_DatosMultas;
		local = (char *(*)(char *, struct svc_req *)) comprobarmultas_1_svc;
		break;

	case Identificacion:
		_xdr_argument = (xdrproc_t) xdr_T_String;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) identificacion_1_svc;
		break;

	case PonerMulta:
		_xdr_argument = (xdrproc_t) xdr_ST_DatosSancion;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) ponermulta_1_svc;
		break;

	case QuitarMulta:
		_xdr_argument = (xdrproc_t) xdr_ST_DatosSancion;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) quitarmulta_1_svc;
		break;

	case AltaVehiculo:
		_xdr_argument = (xdrproc_t) xdr_ST_DatosUsuario;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) altavehiculo_1_svc;
		break;

	case BajaVehiculo:
		_xdr_argument = (xdrproc_t) xdr_ST_DatosUsuario;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) bajavehiculo_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (MULTAS, MULTAS_VER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, MULTAS, MULTAS_VER, multas_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MULTAS, MULTAS_VER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, MULTAS, MULTAS_VER, multas_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MULTAS, MULTAS_VER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
